System:
  FTS_DATABASE_TYPE: SQLite
  FTS_CONNECTION_MESSAGE: Connected
  FTS_OPTIMIZE_API: True
  FTS_MAINLOOP_DELAY: 1
Addresses:
  FTS_COT_PORT: 8087
  FTS_SSLCOT_PORT: 8089
  FTS_DP_ADDRESS: domain.tld
  FTS_USER_ADDRESS: domain.tld
  FTS_API_PORT: 19023
  FTS_FED_PORT: 9000
  FTS_API_ADDRESS: domain.tld
FileSystem:
  FTS_CONFIG_PATH: /opt/FTSConfig.yaml
  FTS_DB_PATH: /opt/FreeTAKServer.db
  FTS_COT_TO_DB: True
  FTS_MAINPATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer
  FTS_CERTS_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs
  FTS_EXCHECK_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/ExCheck
  FTS_EXCHECK_TEMPLATE_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/ExCheck/template
  FTS_EXCHECK_CHECKLIST_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/ExCheck/checklist
  FTS_DATAPACKAGE_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/FreeTAKServerDataPackageFolder
  FTS_LOGFILE_PATH: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/Logs
Certs:
  FTS_SERVER_KEYDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.key
  FTS_SERVER_PEMDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.pem
  FTS_TESTCLIENT_PEMDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/Client.pem
  FTS_TESTCLIENT_KEYDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/Client.key
  FTS_UNENCRYPTED_KEYDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.key.unencrypted
  FTS_SERVER_P12DIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.p12
  FTS_CADIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/ca.pem
  FTS_CAKEYDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/ca.key
  FTS_FEDERATION_CERTDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.pem
  FTS_FEDERATION_KEYDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/server.key
  FTS_CRLDIR: /root/fts.venv/lib/python3.11/site-packages/FreeTAKServer/certs/FTS_CRL.json
  FTS_FEDERATION_KEYPASS: demopassfed
  FTS_CLIENT_CERT_PASSWORD: demopasscert
  FTS_WEBSOCKET_KEY: YourWebsocketKey
